### PR TITLE
fix(validate/links): use 'link-checker' temporarily

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Testing it at https://github.com/sidvishnoi/manifest/pull/1/checks

**Comment by marcoscaceres** [comment]
I'd be happy with this... we could try enabling it for a few specs to see how bad the max request issue is. 

We could also add a warning here and in the docs that this is experimental?

**Comment by sidvishnoi** [comment]
Released v2.3.4 (v2). Let me know here what specs you enable this on, so we can monitor.

**Comment by marcoscaceres** [comment]
Testing https://github.com/w3c/manifest/pull/983

**Comment by sidvishnoi** [comment]
Fixed a regression and re-released. Please run again.

**Pull request merged**
