### PR TITLE
docs: move docs into README.md

### PR DESCRIPTION
**Pull request by marcoscaceres**
Move everything into a single document. Much easier to search/work with.

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Not sure. I preferred them separate. Should probably enable GitHub pages for docs, so we can have both maybe?
We'll also get broken links and many workflows reference links to particular examples/options.

Need to fix headings if we go ahead with this though.

**Comment by marcoscaceres** [comment]
> Not sure. I preferred them separate. Should probably enable GitHub pages for docs, so we can have both maybe?

User feedback (i.e., me) is that this is quite frustrating, having gone through it today. I need to be able to get in/out as quickly as possible, and don't want to be clicking on folders and trying hunt things down in different documents. 

The ideal workflow is: search in browser, copy/pasta, success. 

> We'll also get broken links and many workflows reference links to particular examples/options.
> Need to fix headings if we go ahead with this though.

Sure, happy to do that.

**Comment by marcoscaceres** [comment]
All the links should be good, but let me know. 

If gh-pages works as single page, I'm happy to have that instead of this... but otherwise, I'd strongly prefer we switch to this.

**Comment by marcoscaceres** [comment]
Love it!  Let's go with that.

**Pull request closed without merging**
